### ISSUE TITLE
Disambiguate which version of PatientReader, EventWriter, etc one should use

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/piton#2]
Currently both [src/piton/__init__.py](https://github.com/som-shahlab/piton/blob/main/src/piton/__init__.py) and [src/piton/fileio/__init__.py](https://github.com/som-shahlab/piton/blob/main/src/piton/fileio/__init__.py) specify `EventWriter`, `EventReader`, `PatientReader`, and `PatientWriter` classes. The [demo](https://github.com/som-shahlab/piton/blob/main/demo/script.py) uses the classes specified in [fileio](https://github.com/som-shahlab/piton/blob/main/src/piton/fileio/__init__.py). Is that the right version of these classes to use? If so, can we delete these class specifications from [src/piton/__init__.py](https://github.com/som-shahlab/piton/blob/main/src/piton/__init__.py) and just keep the `Patient` and `Event` classes in that file?

**Comment by Lalaland** [comment]
Arg, the repository was sorta in an inconsistent state since I was mid refactor. I just uploaded a new version which should be consistent.
