### ISSUE TITLE
Support CSVs out-of-the-box (in addition to `.csv.zst`)

### ISSUE THREAD

**Issue by Miking98** [som-shahlab/piton#37]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to first have to manually transform every `.csv` file that I want to feed into the Piton ETL into a `.csv.zst`. This feels unnecessary for smaller datasets (e.g. MIMIC). Especially given `.zst` is a more niche compression format, I think this is confusing/non-obvious to users of the library.

**Describe the solution you'd like**
Add support for directly reading `.csv` files, in addition to `.csv.zst`. 

**Describe alternatives you've considered**
Could have a wrapper function that converts `.csv` into `.csv.zst` and automatically runs (totally transparently to the end user) anytime a `.csv` file is detected.

**Comment by Lalaland** [comment]
Yeah, this is a good idea and should be simple to implement. I'll assign this task to myself.
